from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("login/", views.customer_login, name="customer_login"),
    path("verify-otp/", views.customer_verify_otp, name="customer_verify_otp"),
    path("verify-otp/resend/", views.customer_resend_otp, name="customer_resend_otp"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("notifications/<int:pk>/read/", views.mark_notification_read, name="mark_notification_read"),
    path("customer/", views.customer_dashboard, name="customer_dashboard"),
    path("customer/bookings/new/", views.customer_booking_create, name="customer_booking_create"),
    path("customer/events/", views.customer_events, name="customer_events"),
    path("customer/events/<int:event_id>/register/", views.customer_event_register, name="customer_event_register"),
    path("receipts/<int:receipt_id>/download/", views.receipt_download, name="receipt_download"),
    path("staff/", views.staff_dashboard, name="staff_dashboard"),
    path("staff/member-lookup/", views.member_lookup, name="member_lookup"),
    path("staff/sales/new/", views.sale_create, name="sale_create"),
    path("staff/sessions/new/", views.session_create, name="session_create"),
    path("staff/tasks/<int:task_id>/status/", views.task_status_update, name="task_status_update"),
    path("staff/checklists/<int:item_id>/toggle/", views.checklist_item_toggle, name="checklist_item_toggle"),
    path("partner/", views.partner_dashboard, name="partner_dashboard"),
    path("partner/bookings/", views.manage_bookings, name="manage_bookings"),
    path("partner/bookings/<int:booking_id>/update/", views.booking_status_update, name="booking_status_update"),
    path("partner/events/", views.manage_events, name="manage_events"),
    path("partner/events/new/", views.event_create, name="event_create"),
    path("partner/events/registrations/", views.manage_event_registrations, name="manage_event_registrations"),
    path("partner/events/registrations/<int:registration_id>/update/", views.event_registration_update, name="event_registration_update"),
    path("partner/tasks/", views.manage_tasks, name="manage_tasks"),
    path("partner/tasks/new/", views.task_create, name="task_create"),
    path("partner/checklists/", views.manage_checklists, name="manage_checklists"),
    path("partner/checklists/templates/new/", views.checklist_template_create, name="checklist_template_create"),
    path("partner/checklists/generate/", views.daily_checklist_generate, name="daily_checklist_generate"),
    path("partner/expenses/", views.manage_expenses, name="manage_expenses"),
    path("partner/expenses/new/", views.expense_create, name="expense_create"),
    path("partner/wallet/", views.wallet_ledger, name="wallet_ledger"),
    path("partner/wallet/new/", views.wallet_entry_create, name="wallet_entry_create"),
    path("partner/points/new/", views.point_entry_create, name="point_entry_create"),
    path("partner/staff/", views.manage_staff, name="manage_staff"),
    path("partner/staff/new/", views.staff_create, name="staff_create"),
    path("partner/accounting/", views.accounting_tracker, name="accounting_tracker"),
    path("partner/reports/<str:report_type>.csv", views.export_report, name="export_report"),
]
